import Head from 'next/head';
import Link from 'next/link';
import Layout from '../../components/Layout';

type Props = {
  username: String;
};

export default function SingleTeamPage(props: Props) {
  return (
    <>
      <Head>
        <title>Team Vision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <h1>Welcome to Team xy</h1>
      <Link href="/teams/create-new-event">
        <a>Create Event</a>
      </Link>
    </>
  );
}
