import Head from 'next/head';
import Layout from '../../../components/Layout';
import SubMenu from '../../../components/SubMenu';

type Props = {
  username: String;
  teamId: Number;
};

export default function Exercises(props: Props) {
  return (
    <>
      <Head>
        <title>Team Vision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <SubMenu teamId={props.teamId} />
      <div>
        <h1>Exercises</h1>
      </div>
    </>
  );
}
