import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import * as FaIcons from 'react-icons/fa';
import * as GiIcons from 'react-icons/gi';
import Layout from '../../../components/Layout';
import SubMenu from '../../../components/SubMenu';
import { getUserByValidSessionToken } from '../../../util/database';

type Props = {
  username: String;
  teamId: Number;
  userRoleId: Number;
};

export default function Exercises(props: Props) {
  return (
    <>
      <Head>
        <title>Team Vision - Exercises</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <SubMenu userRoleId={props.userRoleId} teamId={props.teamId} />
      <h1>Exercises</h1>
      <div>
        <div>
          <button>
            <GiIcons.GiBiceps size={20} />
            Arms
          </button>
          <button>Core</button>
          <button>
            <GiIcons.GiLeg size={20} />
            Legs
          </button>
          <button>
            <FaIcons.FaRunning size={20} />
            Agility
          </button>
        </div>
        <div></div>
      </div>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const teamId = context.query.teamId;
  const sessionToken = context.req.cookies.sessionToken;
  const user = await getUserByValidSessionToken(sessionToken);
  const userRoleId = user?.userRoleId;

  return {
    props: {
      userRoleId,
      teamId,
    },
  };
}
