import { css } from '@emotion/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import * as AiIcons from 'react-icons/ai';
import * as BiIcons from 'react-icons/bi';
import * as BsIcons from 'react-icons/bs';
import * as FaIcons from 'react-icons/fa';
import * as GiIcons from 'react-icons/gi';
import * as GrIcons from 'react-icons/gr';
import Layout from '../../../components/Layout';
import SubMenu from '../../../components/SubMenu';
import {
  getEvents,
  getTeamNameById,
  getUserByValidSessionToken,
} from '../../../util/database';
import {
  darkBlue,
  largeText,
  lightBlue,
  lightGrey,
  link,
} from '../../../util/sharedStyles';

// TODO: Create a filter for event types

type Props = {
  username: String;
  teamName: TeamName[];
  teamId: Number;
  events: Event[];
  userRoleId: Number;
};

type Event = {
  id: number;
  eventType: string;
  teamId: number;
  startDay: string;
  endDay: string;
  startTime: string;
  endTime: string;
  meetingTime: string;
  eventLocation: string;
  eventDescription: string;
};

type TeamName = {
  teamName: string;
};

type DeleteEventRequest = {
  id: Number;
};

const mainContainer = css`
  width: 100%;
  display: flex;
`;

const subMenu = css`
  width: 25%;
  position: static;
  background: ${lightGrey};
  display: flex;
  justify-content: flex-start;
  padding: 20px;
  border-right: 2px solid ${darkBlue};
`;

const eventsMainContainer = css`
  display: flex;
  justify-content: center;
  margin-top: 70px;
  margin-bottom: 50px;
  width: 70%;
`;

const eventsContainer = css`
  width: 60%;

  h1 {
    text-align: center;
    margin-bottom: 30px;
    font-size: ${largeText};
    text-transform: uppercase;
    font-weight: 600;
    margin-bottom: 30px;
    word-spacing: 2px;
  }

  > div {
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: 1fr;
    gap: 50px 100px;
    justify-items: stretch;
  }
`;

const eventHeader = css`
  display: flex;
  align-items: center;
  background-image: url('/images/button_background_lightBlue.PNG');
  background-size: cover;
  background-repeat: no-repeat;
  justify-content: space-between;
  border-top-left-radius: 20px;
  border-top-right-radius: 20px;
  padding: 15px 20px;

  div {
    display: flex;
    align-items: center;
    color: white;

    h2 {
      color: white;
      font-size: ${largeText};
      margin-left: 10px;
      text-transform: uppercase;
      margin: 0 0 0 20px;
    }
  }

  button {
    padding: 10px;
    color: #ca2121;
    background: rgba(255, 255, 255, 0.7);
    border-radius: 90%;
    border: none;
    cursor: pointer;
  }
`;

const eventBody = css`
  border-left: 2px solid ${lightBlue};
  border-right: 2px solid ${lightBlue};
  display: flex;
  justify-content: space-evenly;

  padding: 20px;
`;

const eventDate = css`
  display: flex;
  align-items: center;

  h3 {
    padding-left: 10px;
  }
`;

const eventSubBody = css`
  display: flex;
  align-items: center;
  padding-right: 20px;

  p {
    margin-left: 10px;

    span {
      font-weight: 500;
      margin-right: 5px;
    }
  }
`;

const eventInfos = css`
  max-width: 50%;
`;

const eventMessage = css`
  max-width: 50%;
  border-left: 2px solid ${lightBlue};
  padding-left: 20px;

  div {
    display: flex;
    align-items: center;
  }

  h3 {
    padding-left: 10px;
  }
`;

const noEventsContainer = css`
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;

  h2 {
    font-size: ${largeText};
    font-weight: 600;
  }
`;

const eventFooter = css`
  border: 2px solid ${lightBlue};
  border-bottom-left-radius: 20px;
  border-bottom-right-radius: 20px;
  display: flex;
  align-items: center;
  justify-content: space-around;
  padding: 10px 30px;
`;

export default function SingleTeamPage(props: Props) {
  const [allEvents, setAllEvents] = useState(props.events);

  return (
    <>
      <Head>
        <title>Team Vision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div css={mainContainer}>
        <div css={subMenu}>
          <SubMenu userRoleId={props.userRoleId} teamId={props.teamId} />
        </div>

        {props.events.length === 0 ? (
          <div css={noEventsContainer}>
            <h2>There are no events scheduled for this team yet.</h2>
          </div>
        ) : (
          <div css={eventsMainContainer}>
            <div css={eventsContainer}>
              <h1>Welcome to the {props.teamName[0].teamName}</h1>
              <div>
                {allEvents.map((event) => {
                  return (
                    <div key={event.id}>
                      <div css={eventHeader}>
                        <div>
                          {event.eventType === 'Training' ? (
                            <BiIcons.BiDumbbell size={30} />
                          ) : undefined}
                          {event.eventType === 'Tournament' ? (
                            <FaIcons.FaTrophy size={30} />
                          ) : undefined}
                          {event.eventType === 'Social' ? (
                            <GiIcons.GiPartyPopper size={30} />
                          ) : undefined}
                          <h2>{event.eventType}</h2>
                        </div>
                        {props.userRoleId === 1 ? (
                          <button
                            onClick={async (singleEvent) => {
                              singleEvent.preventDefault();

                              const response = await fetch(
                                `/api/teams-by-team-id/events`,
                                {
                                  method: 'DELETE',
                                  headers: {
                                    'Content-Type': 'application/json',
                                  },
                                  body: JSON.stringify({
                                    id: event.id,
                                  }),
                                },
                              );

                              const json =
                                (await response.json()) as DeleteEventRequest;

                              const deleteEvent = () => {
                                // create a copy of the allEvents array
                                const newEventArray = [...allEvents];
                                // find the event.id that has been clicked on
                                const deletedEvent = newEventArray.find(
                                  (e) => e.id === event.id,
                                );
                                // get the index of the event in the copy of the array
                                const deletedEventIndex =
                                  newEventArray.indexOf(deletedEvent);
                                // splice the index out of the array
                                if (deletedEvent) {
                                  newEventArray.splice(deletedEventIndex, 1);
                                }

                                return newEventArray;
                              };
                              // set the state to the result of the function
                              setAllEvents(deleteEvent());
                            }}
                          >
                            <BsIcons.BsTrashFill size={20} />
                          </button>
                        ) : undefined}
                      </div>

                      <div css={eventBody}>
                        <div css={eventInfos}>
                          <div css={eventDate}>
                            <AiIcons.AiOutlineCalendar size={30} />
                            {event.startDay === event.endDay ? (
                              <h3>{event.startDay}</h3>
                            ) : (
                              <h3>
                                {event.startDay} - {event.endDay}
                              </h3>
                            )}
                          </div>

                          <div css={eventSubBody}>
                            <AiIcons.AiOutlineClockCircle size={30} />
                            <p>
                              <span>MEETING: </span>
                              {event.meetingTime}
                            </p>
                          </div>

                          <div css={eventSubBody}>
                            <AiIcons.AiOutlineClockCircle size={30} />
                            <p>
                              <span>START:</span>
                              {event.startTime}
                            </p>
                          </div>

                          <div css={eventSubBody}>
                            <AiIcons.AiOutlineClockCircle size={30} />
                            <p>
                              <span>END:</span>
                              {event.endTime}
                            </p>
                          </div>

                          <div css={eventSubBody}>
                            <GrIcons.GrLocation size={30} />
                            <p>
                              <span>LOCATION:</span>
                              {event.eventLocation}
                            </p>
                          </div>
                        </div>

                        <div css={eventMessage}>
                          <div>
                            <BiIcons.BiMessageDetail size={30} />
                            <h3>Message from your coach</h3>
                          </div>
                          <p>{event.eventDescription}</p>
                        </div>
                      </div>

                      {props.userRoleId === 2 ? (
                        <div css={eventFooter}>
                          <p>Total attendees: 18</p>

                          <Link href={`/teams/${props.teamId}/${event.id}`}>
                            <a css={link}>SEE EVENT DETAILS</a>
                          </Link>
                        </div>
                      ) : (
                        <div css={eventFooter}>
                          <p>Total attendees: 18</p>
                          <Link href={`/teams/${props.teamId}/${event.id}`}>
                            <a css={link}>See event details</a>
                          </Link>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const teamIdString = context.query.teamId;
  const teamId = Number(teamIdString);
  const events = await getEvents(teamId);
  const teamName = await getTeamNameById(teamId);

  const sessionToken = context.req.cookies.sessionToken;

  const user = await getUserByValidSessionToken(sessionToken);
  const userRoleId = user?.userRoleId;

  return {
    props: {
      teamId,
      teamName,
      events,
      userRoleId,
    },
  };
}
