import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Layout from '../../../components/Layout';
import SubMenu from '../../../components/SubMenu';
import { getEvents } from '../../../util/database';

type Props = {
  username: String;
  teamId: Number;
  events: Event[];
};

type Event = {
  id: number;
  eventType: string;
  teamId: number;
  startDay: string;
  endDay: string;
  startTime: string;
  endTime: string;
  meetingTime: string;
  eventLocation: string;
  eventDescription: string;
};

export default function SingleTeamPage(props: Props) {
  return (
    <>
      <Head>
        <title>Team Vision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      {/* <SubMenu teamId={props.teamId} /> */}
      <h1>Welcome to Team xy</h1>
      <Link href={`/teams/${props.teamId}/create-new-event`}>
        <a>Create Event</a>
      </Link>

      {props.events.map((event) => {
        return (
          <div key={event.id}>
            <h2>{event.eventTypeId}</h2>
            <p>{event.startDay}</p>
            <p>{event.meetingTime}</p>
            <p>{event.startTime}</p>
            <p>{event.endTime}</p>
            <p>{event.eventLocation}</p>
            <p>{event.eventDescription}</p>
            {/* <Link>
              <a>See guest list</a>
            </Link> */}
          </div>
        );
      })}
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const teamIdString = context.query.teamId;
  const teamId = Number(teamIdString);

  const events = await getEvents(teamId);
  console.log(events);

  return {
    props: {
      teamId,
      events,
    },
  };
}
