import { css } from '@emotion/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import router from 'next/router';
import { useState } from 'react';
import Layout from '../../components/Layout';
import { getUserByValidSessionToken } from '../../util/database';
import {
  button,
  darkBlue,
  largeText,
  normalText,
} from '../../util/sharedStyles';

type Props = {
  username: string;
  userRoleId: number;
};

export const formContainer = css`
  display: flex;
  align-items: center;
  align-content: center;
  margin-left: 100px;
  height: 90vh;

  @media (max-width: 1024px) {
    padding-left: 40px;
  }

  form {
    display: flex;
    flex-direction: column;
    border: 2px solid ${darkBlue};
    box-shadow: 10px 5px 5px ${darkBlue};
    border-radius: 15px;
    padding: 30px;
    width: 40%;

    h1 {
      color: ${darkBlue};
      font-size: ${largeText};
      text-align: center;
      padding-bottom: 20px;
    }

    h2 {
      color: ${darkBlue};
      font-size: ${normalText};
      font-weight: 400;
      text-align: center;
      padding-bottom: 30px;
    }

    label {
      display: flex;
      flex-direction: column;
      text-align: left;
      color: ${darkBlue};
      font-weight: 600;

      input {
        margin: 5px 0 20px 0;
        width: 100%;
        padding: 5px;
        font-size: ${normalText};
      }
    }
  }
  @media (max-width: 941px) {
    flex-direction: column;
    margin-left: 0;

    form {
      width: 80%;

      h1 {
        font-size: ${largeText};
      }
    }
  }

  @media (max-width: 941px) {
    margin-top: 30px;
    padding: 0;
  }
`;

const imageContainer = css`
  display: flex;
  justify-content: center;
  padding-left: 100px;

  @media (max-width: 996px) {
    width: 70%;
  }

  @media (max-width: 922px) {
    width: 80%;
    margin-top: 20px;
    padding: 0;
  }
`;

export default function CreateNewTeamForm(props: Props) {
  const [teamName, setTeamName] = useState('');
  const [sportType, setSportType] = useState('');
  const [foundedAt, setFoundedAt] = useState('');

  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  if (!props.username) {
    return (
      <Layout>
        <Head>
          <title>User not found!</title>
        </Head>
        <p>Access denied</p>
      </Layout>
    );
  }

  if (props.userRoleId === 2) {
    return (
      <Layout>
        <Head>
          <title>Error</title>
        </Head>
        <p>
          Unfortunately you are not a coach. You are not authorized to visit
          this page.
        </p>
      </Layout>
    );
  }

  return (
    <>
      <Head>
        <title>Team Vision - Create new team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div css={formContainer}>
        <form
          onSubmit={async (event) => {
            event.preventDefault();
            await fetch(`/api/users-by-username/create-new-team`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                teamName: teamName,
                sportType: sportType,
                foundedAt: foundedAt,
              }),
            });

            router.push(`/profiles/${props.username}`);
          }}
        >
          <h1>Your team</h1>
          <h2>
            Tell us your team name and what sport you are planning to play.
          </h2>

          <label htmlFor="Team name">
            Team name
            <input
              data-cy="create-new-team-teamname"
              required
              minLength={3}
              maxLength={50}
              name="Team name"
              placeholder="Chicago Bulls"
              value={teamName}
              onChange={(event) => {
                setTeamName(event.currentTarget.value);
              }}
            />
          </label>

          <label htmlFor="Sport type">
            Sport type
            <input
              data-cy="create-new-team-sporttype"
              required
              minLength={3}
              maxLength={50}
              name="Sport type"
              placeholder="Basketball"
              value={sportType}
              onChange={(event) => {
                setSportType(event.currentTarget.value);
              }}
            />
          </label>

          <label htmlFor="Date of establishment">
            Date of establishment
            <input
              data-cy="create-new-team-date"
              required
              minLength={7}
              maxLength={7}
              name="Date of establishment"
              placeholder="mm/yyyy"
              value={foundedAt}
              onChange={(event) => {
                setFoundedAt(event.currentTarget.value);
              }}
            />
          </label>

          <button data-cy="create-new-team-button" css={button} type="submit">
            CREATE NEW TEAM
          </button>
        </form>
        <div css={imageContainer}>
          <Image
            className="image"
            alt="Logo Icon"
            src="/images/rugby-players.png"
            width="550px"
            height="500px"
          />
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const sessionToken = context.req.cookies.sessionToken;
  const user = await getUserByValidSessionToken(sessionToken);
  const userRoleId = user?.userRoleId ?? null;

  return {
    props: {
      userRoleId,
    },
  };
}
