import { css } from '@emotion/react';
import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import router from 'next/router';
import { useState } from 'react';
import Layout from '../../components/Layout';
import {
  getAllTeamNamesandId,
  getUserByValidSessionToken,
} from '../../util/database';
import {
  button,
  darkBlue,
  largeText,
  normalText,
} from '../../util/sharedStyles';
import { TeamNameandIdforCoach } from '../../util/types';

type Props = {
  username: String;
  allTeamNamesandIdforCoach: TeamNameandIdforCoach[];
  userRoleId: number;
};

export const formContainer = css`
  display: flex;
  align-items: center;
  justify-content: space-around;
  margin: 50px;

  form {
    display: flex;
    flex-direction: column;
    border: 2px solid ${darkBlue};
    box-shadow: 10px 5px 5px ${darkBlue};
    border-radius: 15px;
    padding: 30px;
    width: 40%;

    div {
      display: flex;
    }

    h1 {
      color: ${darkBlue};
      font-size: ${largeText};
      text-align: center;
      padding-bottom: 30px;
    }

    label {
      display: flex;
      flex-direction: column;
      text-align: left;
      color: ${darkBlue};
      font-weight: 600;
      margin-bottom: 5px;

      input,
      select,
      textarea {
        margin: 5px 0 20px 0;
        width: 100%;
        padding: 5px;
        font-size: ${normalText};
      }

      textarea {
        line-height: 40px;
      }

      .neighborInput {
        width: 95%;
      }
    }

    @media (max-width: 1024px) {
      h1 {
        font-size: ${normalText};
      }
    }
  }
  @media (max-width: 768px) {
    flex-direction: column-reverse;

    form {
      width: 70%;
    }
  }
`;

const imageContainer = css`
  display: flex;
  justify-content: center;

  @media (max-width: 1024px) {
    width: 50%;
    padding: 0;
  }

  @media (max-width: 768px) {
    width: 70%;
    margin-top: 10px;
  }
`;

export default function PlayerRequest(props: Props) {
  const [teamChoice, setTeamChoice] = useState('');
  const [positionOnTeam, setPositionOnTeam] = useState('');
  const [playingSince, setPlayingSince] = useState('');
  const [experienceLevel, setExperienceLevel] = useState('');
  const [message, setMessage] = useState('');

  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
  if (!props.username) {
    return (
      <Layout>
        <Head>
          <title>User not found!</title>
        </Head>
        <p>Access denied</p>
      </Layout>
    );
  }

  if (props.userRoleId === 1) {
    return (
      <Layout>
        <Head>
          <title>Error</title>
        </Head>
        <p>You are not authorized to visit this page.</p>
      </Layout>
    );
  }

  return (
    <>
      <Head>
        <title>Team Vision - Player Request</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div css={formContainer}>
        <div css={imageContainer}>
          <Image
            alt="Baseball Player hitting ball"
            src="/images/baseball-player.jpg"
            width="600px"
            height="600px"
          />
        </div>
        <form
          onSubmit={async (event) => {
            event.preventDefault();
            await fetch(`/api/users-by-username/player-request`, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                teamChoice: teamChoice,
                positionOnTeam: positionOnTeam,
                playingSince: playingSince,
                experienceLevel: experienceLevel,
                message: message,
              }),
            });

            router.push(`/profiles/${props.username}`);
          }}
        >
          <h1>Player request</h1>

          <label>
            Which team would you like to apply for?
            <select
              data-cy="player-request-teamChoice"
              id="teamChoice"
              value={teamChoice}
              onChange={(event) => {
                setTeamChoice(event.currentTarget.value);
              }}
            >
              <option>Please select</option>
              {props.allTeamNamesandIdforCoach.map((team) => {
                return (
                  <option key={team.id} value={team.id}>
                    {team.teamName}
                  </option>
                );
              })}
            </select>
          </label>

          <label>
            What position do you plan on playing?
            <input
              data-cy="player-request-position"
              required
              minLength={3}
              maxLength={50}
              placeholder="Defender"
              value={positionOnTeam}
              onChange={(event) => {
                setPositionOnTeam(event.currentTarget.value);
              }}
            />
          </label>

          <div>
            <label>
              Since when have you been playing this sport?
              <input
                data-cy="player-request-playingTime"
                className="neighborInput"
                required
                minLength={7}
                maxLength={7}
                placeholder="mm/yyyy"
                value={playingSince}
                onChange={(event) => {
                  setPlayingSince(event.currentTarget.value);
                }}
              />
            </label>

            <label>
              How would you rate your experience level?
              <select
                data-cy="player-request-experience"
                required
                id="experienceLevel"
                value={experienceLevel}
                onChange={(event) => {
                  setExperienceLevel(event.currentTarget.value);
                }}
              >
                <option>Please select</option>
                <option value="Beginner">Beginner</option>
                <option value="Advanced">Advanced</option>
                <option value="Professional">Professional</option>
              </select>
            </label>
          </div>

          <label>
            Send your message to the coach.
            <textarea
              data-cy="player-request-message"
              required
              minLength={5}
              maxLength={100}
              placeholder="Why do you want to join this team?"
              value={message}
              onChange={(event) => {
                setMessage(event.currentTarget.value);
              }}
            />
          </label>

          <button data-cy="send-request" css={button} type="submit">
            SEND REQUEST
          </button>
        </form>
      </div>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const sessionToken = context.req.cookies.sessionToken;
  const user = await getUserByValidSessionToken(sessionToken);
  const userRoleId = user?.userRoleId ?? null;

  const allTeamNamesandIdforCoach = await getAllTeamNamesandId();

  return {
    props: {
      allTeamNamesandIdforCoach,
      userRoleId,
    },
  };
}
