import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';

const heroDiv = css`
  display: flex;
  justify-content: center;
  align-items: flex-start;

  Image {
    margin-right: 5px;
  }
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Team Vision</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={heroDiv}>
        <Image
          alt="Logo Icon"
          src="/images/logo_blue/logo_blue.png"
          width="90px"
          height="80px"
        />
        <div>
          <h1>Team Vision</h1>
          <h2>Plan smarter, not harder</h2>
        </div>
      </div>
    </div>
  );
}
