import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import * as AiIcons from 'react-icons/ai';
import * as BiIcons from 'react-icons/bi';
import * as CgIcons from 'react-icons/cg';
import * as FiIcons from 'react-icons/fi';
import * as RiIcons from 'react-icons/ri';
import Layout from '../components/Layout';
import {
  darkBlue,
  extralargeText,
  largeText,
  mediumlargeText,
} from '../util/sharedStyles';

const heroDiv = css`
  display: flex;
  justify-content: center;
  align-items: flex-start;

  Image {
    margin-right: 10px;
  }
`;

const sections = css`
  width: 100%;
`;

const mainContainerFirstSection = css`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const firstSection = css`
  background-image: url(/images/background_blue_smoke.PNG);
  background-size: cover;
  background-repeat: no-repeat;
  height: 90vh;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;

  h1 {
    color: white;
    font-size: 5em;
  }

  h2 {
    color: white;
  }

  @media (min-width: 1441px) {
    font-size: ${extralargeText};
  }

  @media (max-width: 656px) {
    font-size: 0.7em;
  }

  @media (max-width: 464px) {
    font-size: 0.6em;

    h1 {
      margin-top: 10px;
    }
  }

  @media (max-width: 396px) {
    padding-left: 20px;
    h1 {
      font-size: 4em;
      margin-top: 10px;
    }
  }
`;

const aboutSubSection = css`
  background-image: url('/images/button_background_lightBlue.PNG');
  background-size: cover;
  background-repeat: no-repeat;
  letter-spacing: 1px;
  width: 100%;

  h3 {
    text-transform: uppercase;
    font-size: 2em;
    color: white;
    padding: 30px 0 20px 20px;
    margin-left: 20px;
    margin-block-start: 0;
    margin-block-end: 0;
  }

  > div {
    width: 100%;
    display: flex;

    div {
      width: 45%;
      color: white;
      font-size: 18px;
      margin: 10px 40px 40px 40px;

      a {
        color: white;
      }
    }
  }

  @media (min-width: 1441px) {
    font-size: ${extralargeText};
    p {
      font-size: ${mediumlargeText};
    }
  }

  @media (max-width: 590px) {
    > div {
      flex-direction: column;

      div {
        width: 80%;
        margin: 0 40px 10px 40px;
      }
    }
  }
`;

const mainContainer = css`
  width: 100%;
`;

const gridContainer = css`
  margin: 30px 120px 20px 120px;
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-template-rows: 1fr;
  gap: 80px 30px;
  justify-items: stretch;

  @media (max-width: 992px) {
    grid-template-columns: 1fr 1fr;
    gap: 10px 30px;
  }

  @media (max-width: 689px) {
    grid-template-columns: 1fr;
    gap: 10px 30px;
  }

  @media (max-width: 482px) {
    margin: 30px 50px 20px 50px;
  }
`;

const gridSubcontainer = css`
  transition: 0.3s;
  margin-top: 20px;

  :hover {
    transform: translate(0, -10px);
  }
`;

const headersForFunctionalites = css`
  display: flex;
  background-image: url('/images/button_background_lightBlue.PNG');
  background-size: cover;
  background-repeat: no-repeat;
  color: white;
  padding: 15px 10px 10px 20px;
  border-top-left-radius: 20px;
  border-top-right-radius: 20px;

  h5 {
    margin-left: 20px;
    font-size: 20px;
    margin-block-start: 0;
    margin-block-end: 0;
  }

  .icon {
    width: 30px;
    height: 30px;
  }
`;

const textBoxforFunctionalities = css`
  border: 1px solid ${darkBlue};
  border-top: none;
  border-bottom-left-radius: 20px;
  border-bottom-right-radius: 20px;
  padding: 20px 80px;
  font-size: 18px;

  @media (min-width: 1441px) {
    font-size: ${mediumlargeText};
  }

  @media (max-width: 1159px) {
    padding: 20px 30px;
  }
`;

const guideSection = css`
  margin-bottom: 60px;

  h3 {
    text-transform: uppercase;
    font-size: 2em;
    padding: 30px 0 20px 20px;
    margin-left: 20px;
    margin-block-start: 0;
    margin-block-end: 0;
  }

  h4 {
    margin: 30px 0 30px 120px;
    font-size: ${largeText};
  }

  @media (min-width: 1441px) {
    font-size: ${extralargeText};
  }

  @media (max-width: 482px) {
    margin-left: 50px;
  }
`;

type Props = {
  username: String;
};

export default function Home(props: Props) {
  return (
    <>
      <Head>
        <title>Team Vision - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout username={props.username} />
      <div css={mainContainer}>
        <section css={firstSection}>
          <div css={mainContainerFirstSection}>
            <div css={heroDiv}>
              <Image
                alt="Logo Icon"
                src="/images/logo_white/teamvision_icon.png"
                width="110px"
                height="100px"
              />
              <div>
                <h1>Team Vision</h1>
                <h2>Plan smarter, not harder</h2>
              </div>
            </div>
          </div>
        </section>

        <section css={sections} id="about">
          <div css={aboutSubSection}>
            <h3>About</h3>
            <div>
              <div>
                <p>
                  Team Vision is a project, that was created for educational
                  purposes, by Andrea Wöger during the Upleveld Fullstack
                  Developer Bootcamp in June 2021.
                </p>
                <p>
                  "I love trying out new sports and getting to know different
                  teams. However, I found that many coaches still use Doodle
                  polls or WhatsApp messages to see which people will show up
                  for upcoming events. Especially in marginal sports, the club's
                  budget often has to be spent sparingly, which means coaches
                  don't want to spend a monthly amount on event planning
                  applications.
                </p>
              </div>
              <div>
                <p>
                  Therefore I wanted to create a free to use application.
                  Coaches and players should get a quick overview about all
                  upcoming trainings, tournaments and socials. Additionally I
                  want to provide a collection of exercises, that players can
                  use for their home workouts, to stay fit throughout the
                  season."
                </p>
                <p>
                  Further functionalities are already in planning and will be
                  implemented as soon as possible. If you have any wishes for
                  new features, please feel free to contact me through our{' '}
                  <Link href="/#contact">
                    <a>contact form</a>
                  </Link>
                  .
                </p>
              </div>
            </div>
          </div>
        </section>

        <section css={guideSection}>
          <h3 id="guide">GUIDE</h3>
          <h4>Functionalities for coaches</h4>

          <div css={gridContainer}>
            <div css={gridSubcontainer}>
              <div css={headersForFunctionalites}>
                <RiIcons.RiTeamLine className="icon" />
                <h5>CREATE TEAMS</h5>
              </div>
              <div css={textBoxforFunctionalities}>
                <p>
                  Ability to create different teams and let your players sign-up
                  for them.
                </p>
              </div>
            </div>

            <div css={gridSubcontainer}>
              <div css={headersForFunctionalites}>
                <FiIcons.FiUserCheck className="icon" />
                <h5>CHECK APPLICANTS</h5>
              </div>
              <div css={textBoxforFunctionalities}>
                <p>
                  Ability to check out a player's application before you can
                  either accept or deny them to the team.
                </p>
              </div>
            </div>

            <div css={gridSubcontainer}>
              <div css={headersForFunctionalites}>
                <AiIcons.AiOutlineCalendar className="icon" />
                <h5>EVENT MANAGEMENT</h5>
              </div>
              <div css={textBoxforFunctionalities}>
                <p>
                  Ability to create, edit and delete events and to see all
                  attending players in one spot.
                </p>
              </div>
            </div>
          </div>
          <h4>Functionalities for players</h4>
          <div css={gridContainer}>
            <div css={gridSubcontainer}>
              <div css={headersForFunctionalites}>
                <CgIcons.CgProfile className="icon" />
                <h5>TEAM SIGN UP</h5>
              </div>
              <div css={textBoxforFunctionalities}>
                <p>
                  Send your favourite team a player request and tell the coach,
                  why you are the best person for their team.
                </p>
              </div>
            </div>

            <div css={gridSubcontainer}>
              <div css={headersForFunctionalites}>
                <AiIcons.AiOutlineCalendar className="icon" />
                <h5>EVENT SIGN UP</h5>
              </div>
              <div css={textBoxforFunctionalities}>
                <p>
                  See all upcoming events for the season and let the coach and
                  your co-players know, if you are attending or not.
                </p>
              </div>
            </div>

            <div css={gridSubcontainer}>
              <div css={headersForFunctionalites}>
                <BiIcons.BiDumbbell className="icon" />
                <h5>EXERCISES</h5>
              </div>
              <div css={textBoxforFunctionalities}>
                <p>
                  Have a collection of exercises for your home workouts to keep
                  you fit throughout the season and to make your coach proud.
                </p>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
